---
title: "Divvy Tripdata Database"
author: "Seif Kungulio"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

#Install the following libraries if required
if(!requireNamespace("RPostgres", quietly = TRUE)){
  # If not installed, then install it
  install.packages("RPostgres")
}
if(!requireNamespace("DBI", quietly = TRUE)){
  # If not installed, then install it
  install.packages("DBI")
}
if(!requireNamespace("ini", quietly = TRUE)){
  # If not installed, then install it
  install.packages("ini")
}

# Install necessary libraries
library(RPostgres)
library(DBI)
library(ini)
```

## Introduction



## Divvy Database Creation

### Database connection
Establish postgresql database connection
```{r db_connection}
# Read config
config <- read.ini("resources/db_config.ini")
db <- config$postgresql

# Safe database connection
tryCatch({
  con <- dbConnect(
    Postgres(),
    host = db$host,
    dbname = db$database,
    user = db$user,
    password = db$password,
    port = as.integer(db$port)
  )
}, error = function(e) {
  stop("Database connection failed: ", e$message)
})

knitr::opts_chunk$set(connection = con)
```

### Database schema
Create database schema to the database
```{sql}
CREATE SCHEMA IF NOT EXISTS divvy;
```

### Databse tables


### Database views


### Database functions



## Exploratory Data Analysis



## Conclusion